spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  time-zone:
    kr: Asia/Seoul
    us: America/New_York
